# Generated by Django 2.2.4 on 2019-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='TITLE', max_length=100)),
                ('text1', models.TextField()),
                ('bool1', models.BooleanField(default=False)),
                ('int1', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
